spring:
  profiles:
    active: '@spring.profiles.active@'
---
server:
  port: 8081
  servlet:
    context-path: /sistema-backend
spring:
  profiles: dev   
  application:
    name: sisnna-upe-backend
#  datasource:
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    jdbcUrl: "jdbc:oracle:thin:@localhost:1521:xe"
#    username: "SISNNA_UPE"
#    password: "SISNNA_UPE"
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 30000
---
spring:
  profiles: qa   
  application:
    name: sisnna-upe-backend
#  datasource:
#    jndi-name: jdbc/SisnnaUpeDS
#    driver-class-name: oracle.jdbc.OracleDriver
---
spring:
  profiles: prd   
  application:
    name: sisnna-upe-backend
#  datasource:
#    jndi-name: jdbc/SisnnaUpeDS
#    driver-class-name: oracle.jdbc.OracleDriver